-- 007 — Quellen-Register für die portierten Connectoren (FK-Anker + Tier/Provenienz für Priorisierung).
-- Idempotent. Namen aus den Connector-Objekten, Schedule 3×/Tag.

INSERT INTO quellen (id, name, typ, tier, provenienz, abruf_intervall) VALUES
  ('0001', 'Autobahn-API (verkehr.autobahn.de)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0110', 'GST-Routen Hamburg (Großraum-/Schwertransport-Netz, LBV/LGV)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0111', 'Brücken & Ingenieurbauwerke Hamburg (LSBG)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0112', 'Baustellen Hamburg (stadtweit, BVM/LGV)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0113', 'Bedarfsumleitungen Hamburg (BWVI)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0114', 'Berlin VIZ — Baustellen/Sperrungen/Störungen (mdhwfs)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0115', 'Berlin VIZ — GeoJSON-Feeds (Verkehrsredaktion + TIC3)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0116', 'Detailnetz Berlin — Ingenieurbauwerke (Brücken/Tunnel)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0117', 'Straßenbaustellen Schleswig-Holstein (LBV.SH / GDI-SH)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0118', 'Umleitungsstrecken Schleswig-Holstein (LBV.SH / GDI-SH)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0119', 'Straßenbaustellen Mecklenburg-Vorpommern (LS M-V / SBV)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0120', 'LSBB Sperrinfo Sachsen-Anhalt (SPERRINFOSYS ST)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0121', 'GST-Negativkarten Sachsen (LASuV) — gesperrte Brücken (PDF je Landkreis)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0122', 'MobiData BW — Verkehrsmeldungen (LMS BW)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0123', 'BAYSIS Bauwerke (Bayerische Straßenbauverwaltung)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0124', 'GST-Schwertransportkarte NRW (lastbeschränkte Brücken)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0125', 'OpenGeodata.NRW / Straßen.NRW — Bauwerke (Brücken/Tunnel)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0126', 'Hessen Mobil — Lastbeschränkte Brücken (GST-gesperrt)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0127', 'baustellen.saarland (Landesbetrieb für Straßenbau)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0128', 'MobiData BW — Baustelleninformationen (BEMaS)', 'api', 'T1', 'amtlich', '0 8,12,18 * * *'),
  ('0210', 'München — Baustellen (GeoPortal München, mor_wfs)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0211', 'Aachen — Baustellen (BSIS, Baustellen-Informationssystem)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0212', 'Köln — Verkehrsbeeinträchtigungen (ArcGIS Verkehrskalender)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0213', 'Dresden — Verkehrseinschränkungen (Themenstadtplan, kommisdd OGC API)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0214', 'Stuttgart — Baustellen (Open Data Stuttgart, geoserver.stuttgart.de)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0215', 'Münster — Baustellen (geo.stadt-muenster.de, MapServer WFS)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0216', 'Dortmund — Baustellen (Opendatasoft)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0217', 'Düsseldorf — Verkehrsmeldungen (DATEX-II Mobilitätsdaten)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0218', 'Bonn — Baustellen (stadtplan.bonn.de)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0219', 'Karlsruhe / TRK — Baustellen (TechnologieRegion Karlsruhe)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0220', 'Leipzig — Verkehrsraumeinschränkungen', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0221', 'Leipzig — Verkehrszeichen-Kataster (GST-Beschränkungen)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0222', 'Rostock — Baustellen (OpenData.HRO)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0223', 'Rostock — GST gesperrte Ingenieurbauwerke (OpenData.HRO)', 'api', 'T4', 'amtlich', '0 8,12,18 * * *'),
  ('0301', 'Overpass API (OpenStreetMap)', 'api', 'T5', 'crowdsourced', '0 8,12,18 * * *'),
  ('0302', 'RVR / GEONETZWERK.RUHR — Baustellen', 'api', 'T1', 'amtlich', '0 8,12,18 * * *')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, tier=EXCLUDED.tier, provenienz=EXCLUDED.provenienz, abruf_intervall=EXCLUDED.abruf_intervall;
